name: JoomHost Slider
slug: hostsite-slider
groups: JoomHost
form:
  general:
    - name: sliders
      type: group-repeater
      schema:
        - name: title
          value: Slide Title

        - name: title_tag
          type: select
          label: Title Tag
          value: h3
          options:
            h1: H1
            h2: H2
            h3: H3
            h4: H4
            h5: H5
            h6: H6
            div: DIV

        - name: sub_title
          value: Slider Sub Title

        - name: sub_title_position
          type: select
          value: aft
          options:
            bft: Before Title
            aft: After Title

        - name: content
          type: editor
          value: content

        - name: button_enabled
          type : switch
          label: Enabled Button

        - name: button
          type: link
          depends:
            button_enabled: true

        - name: enable_image
          type: switch

        - name: image
          type: file-manager
          label: Object Image
          help: If defined, this image will be used as the background for this slide. To remove a background image, simply delete the URL from the settings field.
          depends:
            enable_image: true

        - name: alt_text
          type: text
          depends:
            enable_image: true

        - name: image_width
          type: text
          value: 570px
          depends:
            enable_image: true

        - name: image_position
          type: select
          value: right
          options:
            left: Left
            right: Right
            bottom: Bottom
          depends:
            enable_image: true

        - name: bg_color
          type: color
          lable: Background Color

        - name : bg_overlay
          label: Background Overlay
          type: switch

      value:
        - title: Slide Title

    - name: alignment
      label : Horizontal Alignment
      type: select
      value: center
      image: true
      responsive: true
      options:
        left: Left
        right: Right
        center: Center

    - name: v_center
      label : Vertica Center Text
      type: switch

    - name : slider_height
      type: select
      value : custom
      options:
        custom : Custom Height
        full : Full Height

    - name : custom_height
      type: slider
      max : 1000
      step : 10
      value: 400
      suffix: px
      depends :
        slider_height : custom

    - name: utilities
      type: divider

    - name: arrows
      type: switch
      value: true
      help: This setting allows you to turn the navigation arrows on or off.

    - name: dots
      type: switch
      label: Dots Navigation
      value: true
      help: Disabling this option will remove the circle button at the bottom of the slider.

    - name: autoplay
      type: switch
      labe: Auto Play
      value: true
      help: If you would like the slider to slide automatically, without the visitor having to click the next button.

    - name: autoplay_speed
      type: text
      label: Autoplay Speed
      value: 5000
      help: Autoplay Speed in milliseconds
      depends:
        autoplay: true

  styles:

    - name: title_styles
      type: divider

    - name: header_font
      type: typography
      label: Font

    - name: header_color
      type: color
      label: Color

    - name : header_margin
      type: margin
      label: Margin

    - name: header_span_note
      type: divider
      label: Wrap words from title text with <span> will apply this styles. Eg - Hello <span>Beautiful</span> World.

    - name : header_span_font
      type: typography
      label: Span Font

    - name : header_span_color
      type: color
      label: Span Color

    - name : header_span_newline
      type : switch
      label: Span New Line

    - name: sub_title_divider
      type: divider

    - name: sub_title_color
      type: color

    - name: sub_title_font
      type: typography

    - name: sub_title_margin
      type: margin

    - name: content_styles
      type: divider

    - name: body_font
      type: typography
      label: Font

    - name: body_color
      type: color
      label: Color

    - name: body_margin
      type: margin
      type: Margin

    - name: image_divider
      type: divider

    - name: image_margin
      type: margin

    - name: button_styles
      type: divider

    - name: button_font
      type: typography
      label: Font

    - name: button_style
      type: switch
      label: Custom Style
      help: Enable this for custom button style.

    - name: button_bg
      type: color
      label: Background Color
      depends:
        button_style : true

    - name: button_text
      type: color
      label: Text Color
      depends:
        button_style : true

    - name: button_border_width
      type: slider
      label: Border Width
      suffix: px
      depends:
        button_style : true

    - name: button_border_color
      type: color
      label: Border Color
      depends:
        button_style : true

    - name: button_border_radius
      type: slider
      label: Border Radius
      suffix: px
      depends:
        button_style : true

    - name: button_bg_hover
      type: color
      label: Hover Background Color
      depends:
        button_style : true

    - name: button_text_hover
      type: color
      label: Hover Text Color
      depends:
        button_style : true

    - name: button_border_color_hover
      type: color
      label: Hover Border Color
      depends:
        button_style : true

    - name: button_padding
      type: padding

    - name : button_margin
      type : margin

    - name: misc_styles
      type: divider

    - name: arrow_color
      type: color
      label: Arrow Color
      depends :
        arrows : true

    - name: dots_color
      type: color
      label: Dots Nav Color
      depends :
        dots : true

    - name: padding
      type: padding

  animation :

    - name : slider_items_animation
      type : divider

    - name: title_animation
      type: select
      help: Animation apply on slider title. Live example of all animations is here - bit.ly/quix-demo
      value: fadeInDown
      options:
        0: None
        fadeIn : Fade In
        fadeInDown : Fade In Down
        fadeInLeft : Fade In Left
        fadeInRight : Fade In Right
        fadeInUp : Fade In Up
        bounceIn : Bounce In
        bounceInDown : Bounce In Down
        bounceInLeft : Bounce In Left
        bounceInRight : Bounce In Right
        bounceInUp : Bounce In Up
        slideInUp : Slide In Up
        slideInDown : Slide In Down
        slideInLeft : Slide In Left
        slideInRight : Slide In Right
        rotateIn : Rotate In
        rotateInDownLeft : Rotate In Down Left
        rotateInDownRight : Rotate In Down Right
        rotateInUpLeft : Rotate In Up Left
        rotateInUpRight : Rotate In Up Right
        zoomIn : Zoom In
        zoomInDown : Zoom In Down
        zoomInLeft : Zoom In Left
        zoomInRight : Zoom In Right
        zoomInUp : Zoom In Up
        flipInX : Flip In X
        flipInY : Flip In Y
        lightSpeedIn : Light Speed In
        rollIn : Roll In

    - name: content_animation
      type: select
      help: Animation apply on slider content. Live example of all animations is here - bit.ly/quix-demo
      value: fadeInDown
      options:
        0: None
        fadeIn : Fade In
        fadeInDown : Fade In Down
        fadeInLeft : Fade In Left
        fadeInRight : Fade In Right
        fadeInUp : Fade In Up
        bounceIn : Bounce In
        bounceInDown : Bounce In Down
        bounceInLeft : Bounce In Left
        bounceInRight : Bounce In Right
        bounceInUp : Bounce In Up
        slideInUp : Slide In Up
        slideInDown : Slide In Down
        slideInLeft : Slide In Left
        slideInRight : Slide In Right
        rotateIn : Rotate In
        rotateInDownLeft : Rotate In Down Left
        rotateInDownRight : Rotate In Down Right
        rotateInUpLeft : Rotate In Up Left
        rotateInUpRight : Rotate In Up Right
        zoomIn : Zoom In
        zoomInDown : Zoom In Down
        zoomInLeft : Zoom In Left
        zoomInRight : Zoom In Right
        zoomInUp : Zoom In Up
        flipInX : Flip In X
        flipInY : Flip In Y
        lightSpeedIn : Light Speed In
        rollIn : Roll In

    - name: btn_animation
      type: select
      help: Animation apply on slider button. Live example of all animations is here - bit.ly/quix-demo
      value: fadeInUp
      options:
        0: None
        fadeIn : Fade In
        fadeInDown : Fade In Down
        fadeInLeft : Fade In Left
        fadeInRight : Fade In Right
        fadeInUp : Fade In Up
        bounceIn : Bounce In
        bounceInDown : Bounce In Down
        bounceInLeft : Bounce In Left
        bounceInRight : Bounce In Right
        bounceInUp : Bounce In Up
        slideInUp : Slide In Up
        slideInDown : Slide In Down
        slideInLeft : Slide In Left
        slideInRight : Slide In Right
        rotateIn : Rotate In
        rotateInDownLeft : Rotate In Down Left
        rotateInDownRight : Rotate In Down Right
        rotateInUpLeft : Rotate In Up Left
        rotateInUpRight : Rotate In Up Right
        zoomIn : Zoom In
        zoomInDown : Zoom In Down
        zoomInLeft : Zoom In Left
        zoomInRight : Zoom In Right
        zoomInUp : Zoom In Up
        flipInX : Flip In X
        flipInY : Flip In Y
        lightSpeedIn : Light Speed In
        rollIn : Roll In
