name: Joomhost Smart Tab
slug: hostsite-smart-tabs
groups: JoomHost
form:
  general:
    - name: tabs
      type: group-repeater
      schema:
        - name: title
          value: Tab Title

        - name: sub_title
          value: Sub Title

        - name: enable_icon
          type: switch

        - name: select_icon
          type: select
          options:
            icon: Icon
            image: Image
          depends:
            enable_icon: true

        - name: icon
          type: icon
          depends:
            select_icon: icon

        - name: image
          type: file-manager
          depends:
            select_icon: image

        - name: trigger_id
          type: text

      value:
        - title: Tab Title

    - name: active_first_item
      label: Active Target
      type: switch

    - name: style
      type: select
      value: tabs
      options:
        tabs: Tabs
        pills: Pills
        vertical: Vertical

    - name: nav_width
      type: slider
      value: 10
      min: 0
      max: 100
      suffix: %
      depends:
        style: vertical

    - name: tab_content_width
      type: slider
      value: 90
      min: 0
      max: 100
      suffix: %
      depends:
        style: vertical

  styles:
    - name: title_divider
      type: divider
      label: Trigger Title

    - name: title_font
      type: typography

    - name: title_color
      type: color

    - name: trigger_sub_title
      type: divider

    - name: sub_title_font
      type: typography

    - name: sub_title_color
      type: color

    - name: trigger_divider
      type: divider

    - name: trigger_bg
      type: color

    - name: trigger_arrow_color
      type: color

    - name: trigger_bg_hover
      type: color

    - name: trigger_margin
      type: margin

    - name: trigger_padding
      type: padding

    - name: border
      type: switch
      label: Border Styling

    - name: border_width
      type: slider
      label: Border Width
      value: 2
      depends:
        border: true

    - name: border_radius
      type: slider
      label: Border Radius
      value: 3
      depends:
        border: true

    - name: border_style
      type: select
      value: solid
      depends:
        border: true
      options:
        solid: Solid
        dotted: Dotted
        dashed: Dashed
        double: Double
        groove: Groove
        ridge: Ridge
        inset: Inset
        outset: Outset

    - name: border_color
      type: color
      label: Border Color
      depends:
        border: true

    - name: border_hover_color
      type: color
      label: Border Hover Color
      depends:
        border: true

    - name: nav_tab_divider
      type: divider

    - name: nav_tab_bg
      type: color

    - name: nav_tab_padding
      type: padding

    - name: nav_tab_margin
      type: margin

    - name: content_divider
      type: divider

    - name: nav_content_bg
      type: color

    - name: content_padding
      type: padding

    - name: content_margin
      type: margin

    - name: globar_divider
      type: divider

    - name: margin
      type: margin

    - name: padding
      type: padding
